### GET request to example server
POST localhost:3000/api/products
Content-Type: application/json

{
  "id": 1,
  "name": "Mechanical Keyboard",
  "sku": "KB-001",
  "description": "RGB mechanical keyboard",
  "price": 2500,
  "quantity": 25,
  "categoryId": 1
}
###

DELETE localhost:3000/api/products/1

